"""
Data models for the OVOS Plugin Arena.

The arena is fully static: every artifact is a JSON file generated by CI and
committed to the repository.  These models define the contracts for those
artifacts — prediction rows (§3.2), assembled battles, benchmark boards, ELO
boards, and the data index consumed by the static frontend.
"""

from __future__ import annotations

import enum
import hashlib
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Modality(str, enum.Enum):
    """Supported arena modalities — each is an independent league with its
    own benchmarks, battles and ELO standings.

    Leagues are keyed by *training-data format*, never by strategy: keyword-
    paradigm and template-paradigm intent engines consume different
    supervision (hand-written vocabulary rules vs phrase-template corpora),
    so they compete in separate leagues; the open ``intent`` league hosts
    mixed-paradigm pipeline fusions. A single-stage embedding classifier is
    not a league of its own — it is a *strategy* trained from one of these
    two data formats (see ``runner/intent_pipeline.py`` ``EngineSpec.paradigm``)
    and competes within that format's league.

    §R# — each of the three intent leagues now runs its own ELO pool (own
    battles, own ``elo-seed``/``leaderboard`` files) instead of collapsing
    into a shared ``intent`` battle group; see ``battle_group()`` below and
    docs/methodology.md.
    """

    TTS = "tts"
    STT = "stt"
    WAKE_WORD = "wake_word"
    VAD = "vad"
    INTENT = "intent"  # open league — mixed-paradigm pipeline fusions
    INTENT_TEMPLATE = "intent_template"  # template-paradigm engines
    INTENT_KEYWORD = "intent_keyword"  # keyword-paradigm engines
    # Streaming wake-word league (§A3.2 / R15): same fighters as WAKE_WORD,
    # a separate benchmark board scored from continuous-audio detection
    # events rather than isolated clips (arena.metrics.score_ww_stream).
    WW_STREAM = "ww_stream"
    # Grapheme-to-phoneme league (§A6) — vote-less: benchmark boards only
    # (phoneme error rate, provenance-tiered gold), no battles/ELO/votes.
    # See VOTELESS_MODALITIES below and arena.metrics.score_g2p.
    G2P = "g2p"


INTENT_MODALITIES = frozenset(
    {Modality.INTENT.value, Modality.INTENT_TEMPLATE.value,
     Modality.INTENT_KEYWORD.value}
)


def is_intent_modality(modality: str) -> bool:
    return modality in INTENT_MODALITIES


# §A6 — leagues with no battles/ELO/votes at all: benchmark boards only.
# ``cmd_assemble`` (arena/cli.py) MUST NOT emit ``battles-*``/``elo-seed-*``/
# ``leaderboard-*`` artifacts for these modalities, and the prune/superseded-
# artifact guard (``_clean_merged_artifacts``) must not treat a missing
# leaderboard here as something to regenerate. ``ww_stream`` is *not* listed:
# it is benchmark-only in practice (no registered eval dataset publishes
# votes), but its identity battle_group mapping was never explicitly gated,
# so leaving it out preserves existing behaviour exactly.
VOTELESS_MODALITIES = frozenset({Modality.G2P.value})


def battle_group(modality: str) -> str:
    """The blind-battle / ELO group a modality competes in.

    §R# — each league is its own battle group (identity mapping): the three
    intent leagues (``intent``, ``intent_template``, ``intent_keyword``) each
    get a fully separate battles pool, ELO seed and leaderboard — a template
    engine is never paired against a keyword engine, and the open ``intent``
    fusion league never pools with either paradigm-pure league. Benchmark
    *boards* were already per-modality (paradigm-pure) and stay that way.

    ``ww_stream`` keeps its existing (unchanged) identity mapping: it is a
    benchmark-only modality (see ``arena.metrics.score_ww_stream``) that
    never produces its own battles/ELO artifacts, so ``battle_group`` maps
    it to itself exactly as before this change.
    """
    return modality


# ---------------------------------------------------------------------------
# Leagues — the frontend's single source of truth for tabs
# ---------------------------------------------------------------------------

# Display label per league, and the tab order the leaderboard page renders
# them in. This is the ONE place these are defined — the frontend derives its
# tabs from ``LEAGUES`` (via data/index.json) instead of hardcoding them.
LEAGUE_LABELS: dict[str, str] = {
    Modality.INTENT_TEMPLATE.value: "Intent · Template",
    Modality.INTENT_KEYWORD.value: "Intent · Keyword",
    Modality.INTENT.value: "Intent · Fusions",
    Modality.STT.value: "STT",
    Modality.TTS.value: "TTS",
    Modality.WAKE_WORD.value: "Wake Word",
    Modality.VAD.value: "VAD",
    Modality.G2P.value: "G2P",
}

LEAGUE_ORDER: tuple[str, ...] = (
    Modality.INTENT_TEMPLATE.value,
    Modality.INTENT_KEYWORD.value,
    Modality.INTENT.value,
    Modality.STT.value,
    Modality.TTS.value,
    Modality.WAKE_WORD.value,
    Modality.VAD.value,
    Modality.G2P.value,
)


def leagues() -> list[dict[str, Any]]:
    """League descriptors for ``data/index.json``: ``{id, label, battle_group,
    order, voteless}`` in tab order, one per :class:`Modality`. §R# — each of
    the three intent leagues is now its own battle_group (identity mapping);
    they no longer collapse into a shared ``"intent"`` pool. §A6 —
    ``voteless`` (True for `g2p`) tells the frontend to skip the ladder
    section entirely rather than render an always-empty one."""
    return [
        {
            "id": modality,
            "label": LEAGUE_LABELS[modality],
            "battle_group": battle_group(modality),
            "order": i,
            "voteless": modality in VOTELESS_MODALITIES,
        }
        for i, modality in enumerate(LEAGUE_ORDER)
    ]


class VoteOutcome(str, enum.Enum):
    """Outcome of a single blind battle vote."""

    CANDIDATE_A = "candidate_a"
    CANDIDATE_B = "candidate_b"
    TIE = "tie"
    BOTH_WRONG = "both_wrong"


class VoteSource(str, enum.Enum):
    """Whether a vote was cast by a human or derived from benchmark metrics."""

    HUMAN = "human"
    AUTO_BENCHMARK = "system:benchmark"  # §4 R5 — ELO seeding from metrics


# ---------------------------------------------------------------------------
# Prediction rows (§3.2 contract)
# ---------------------------------------------------------------------------


class PredictionRow(BaseModel):
    """One prediction for one sample by one competitor (§3.2).

    Stored as JSON lines in ``predictions/<competitor_id>.jsonl`` inside an
    HF dataset repo.  Modality-specific payload fields are kept in ``extras``
    when not modelled explicitly.
    """

    competitor_id: str
    sample_id: str
    dataset_id: str
    lang: str
    plugin_id: str
    modality: str | None = None  # league; inferred from fields when absent
    # §4 A2 schema convergence — 2 is the canonical §3.2 row contract this
    # class defines; legacy STTRow-shaped rows are converted to it at load
    # time (arena.predictions) and get schema_version 1 to mark provenance.
    schema_version: int = 2
    plugin_version: str = ""
    prediction: str | None = None
    runner_version: str = ""
    created_at: str = ""
    # intent modality
    utterance: str | None = None
    reference_intent: str | None = None
    exact_match: bool | None = None
    confidence: float | None = None
    bucket: str | None = None
    reference_slots: dict[str, str] | None = None
    predicted_slots: dict[str, str] | None = None
    # stt modality
    reference_text: str | None = None
    wer: float | None = None
    # tts modality — source text read aloud; ``prediction`` holds the audio ref
    input_text: str | None = None
    # wake_word modality — ground-truth presence ("positive"/"negative"),
    # ``prediction`` holds the detector decision
    label: str | None = None
    # audio stimulus URL for the voter (source clip for stt/wake_word;
    # synthesised clip for tts when ``prediction`` is not itself a URL)
    audio_url: str | None = None
    # shared diagnostics
    latency_ms: float | None = None
    # performance-metrics campaign M1 — additive, optional (runner.perf):
    # elapsed_ms is the wall time of the single inference call
    # (time.perf_counter-based); peak_rss_mb is a rough, process-wide RSS
    # sample bracketing that call (see runner.perf.measure_call for the
    # caveats — not a true peak, not attributable to this call alone);
    # audio_secs is the duration of the input audio (stt/wake_word) or
    # produced audio (tts), letting RTF = elapsed_ms / 1000 / audio_secs be
    # computed downstream; hw is the per-run hardware fingerprint (runner.
    # perf.hw_fingerprint). All default to None/empty — the vast majority of
    # already-published rows predate this capture and MUST stay valid.
    elapsed_ms: float | None = None
    peak_rss_mb: float | None = None
    audio_secs: float | None = None
    hw: dict[str, Any] | None = None
    extras: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Battles
# ---------------------------------------------------------------------------


def battle_id_for(
    modality: str, dataset_id: str, lang: str, sample_id: str,
    competitor_a: str, competitor_b: str,
) -> str:
    """Deterministic battle id — stable across assemble runs so votes stay valid.

    Competitors are sorted before hashing: the battle between (x, y) is the
    same battle as (y, x).
    """
    lo, hi = sorted((competitor_a, competitor_b))
    key = "|".join((modality, dataset_id, lang, sample_id, lo, hi))
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]


class Battle(BaseModel):
    """One assembled blind A/B battle, serialised into the battles pool."""

    battle_id: str
    modality: Modality
    dataset_id: str
    lang: str
    sample_id: str
    # candidate payloads — what the voter sees (NO competitor identity)
    input_text: str | None = None  # utterance (intent) / source text (tts)
    audio_url: str | None = None  # source audio clip (stt / wake_word)
    reference: str | None = None  # gold label / reference transcript
    prediction_a: Any | None = None
    prediction_b: Any | None = None
    # identity — revealed by the UI only after the vote is cast
    competitor_a: str
    competitor_b: str
    plugin_a: str = ""
    plugin_b: str = ""


class BattlesPool(BaseModel):
    """``battles-<modality>-<lang>.json`` artifact."""

    modality: Modality
    dataset_id: str
    lang: str
    generated_at: str
    dataset_info: dict[str, Any] | None = Field(
        None,
        description=(
            "Registry metadata for the eval corpus, including the "
            "paradigm-specific training corpora the fighters trained on."
        ),
    )
    battles: list[Battle] = Field(default_factory=list)
    # Count of candidate pairs dropped by assemble_battles because their
    # reference text disagreed despite sharing a sample_id (colliding legacy
    # ids across pre-#70 shards) — 0 when the assembler found none. Surfaces
    # the guard's effect instead of letting mismatched pairs vanish silently.
    skipped_reference_mismatches: int = 0


# ---------------------------------------------------------------------------
# Boards
# ---------------------------------------------------------------------------


class BenchmarkEntry(BaseModel):
    """One competitor row in an auto-metric benchmark board."""

    rank: int = 0
    competitor_id: str
    plugin_id: str = ""
    samples: int = 0
    metrics: dict[str, float] = Field(default_factory=dict)
    # Bootstrap 95% CI on ``metrics[primary_metric]`` (§4 A1.2, see
    # arena/metrics.py:primary_metric_ci) — None when the modality has no CI
    # strategy or too few scoreable rows.
    primary_metric_ci_lower: float | None = None
    primary_metric_ci_upper: float | None = None
    # True when this entry's CI overlaps the #1-ranked entry's CI — the
    # frontend should show these entries as "≈ tied with #1" rather than
    # implying the point-estimate ordering is statistically significant.
    tied_with_leader: bool = False
    # §G version-blend guard: distinct ``plugin_version`` values seen across
    # this competitor's rows, and whether more than one was blended into a
    # single metrics aggregate. A single-version competitor always has
    # exactly one entry here and ``version_blended=False``.
    plugin_versions: list[str] = Field(default_factory=list)
    version_blended: bool = False
    # A run that produced zero scored samples (or never computed the primary
    # metric at all) has no signal to rank on — leaving it at ``rank=0`` from
    # a bare sort would let it land at #1 whenever it's the board's only or
    # first-sorted entry (e.g. a solo fighter whose entire run failed).
    unranked: bool = False
    unranked_reason: str | None = None


class BenchmarkBoard(BaseModel):
    """``benchmark-<modality>-<lang>.json`` — metrics straight from predictions."""

    modality: Modality
    dataset_id: str
    lang: str
    generated_at: str
    primary_metric: str
    dataset_info: dict[str, Any] | None = Field(
        None,
        description=(
            "Registry metadata for the eval corpus: url, license, notes, "
            "and the HF predictions repo(s) the board was assembled from."
        ),
    )
    predictions_revisions: dict[str, str] | None = Field(
        None,
        description=(
            "Map from HF predictions repo id to the immutable commit SHA it "
            "was pinned to for this board (§C reproducibility) — lets a "
            "third party re-fetch the exact predictions that produced any "
            "row here, instead of a floating branch."
        ),
    )
    wer_normalizer_version: int | None = Field(
        None,
        description=(
            "STT boards only: the ``arena.metrics.WER_NORMALIZER_VERSION`` "
            "used to score this board's WER metrics, so past scores stay "
            "distinguishable from future normalizer revisions."
        ),
    )
    entries: list[BenchmarkEntry] = Field(default_factory=list)


class EloEntry(BaseModel):
    """One competitor row in an ELO board."""

    rank: int = 0
    competitor_id: str
    plugin_id: str = ""
    elo: float
    battles: int = 0
    wins: int = 0
    losses: int = 0
    ties: int = 0
    win_rate: float = 0.0
    human_votes: int = 0
    auto_votes: int = 0
    # Bradley-Terry batch rating (§4, arena/rating.py) — order-independent,
    # with a bootstrap 95% confidence interval. ``elo`` above is the legacy
    # sequential rating, kept as a secondary display column; ``rank`` is
    # derived from ``bt_rating``, not ``elo``.
    bt_rating: float | None = None
    ci_lower: float | None = None
    ci_upper: float | None = None


class EloBoard(BaseModel):
    """``leaderboard-<modality>-<lang>.json`` — seeded ELO + human votes."""

    modality: Modality
    lang: str
    generated_at: str
    vote_count: int = 0
    human_vote_count: int = 0
    # True when human_vote_count < rating.PROVISIONAL_MIN_HUMAN_VOTES — the
    # board is ranked from the benchmark-derived seed with too few human
    # votes yet to narrow the bootstrap CIs meaningfully; the frontend
    # should show a "provisional" badge rather than a firm ranking.
    provisional: bool = True
    entries: list[EloEntry] = Field(default_factory=list)


class EloSeed(BaseModel):
    """``elo-seed-<modality>-<lang>.json`` — deterministic benchmark-derived ELO.

    Written by ``assemble``; ``tally`` replays human votes on top of it.
    """

    modality: Modality
    lang: str
    generated_at: str
    auto_vote_count: int = 0
    ratings: dict[str, float] = Field(default_factory=dict)
    battles: dict[str, int] = Field(default_factory=dict)
    wins: dict[str, int] = Field(default_factory=dict)
    losses: dict[str, int] = Field(default_factory=dict)
    ties: dict[str, int] = Field(default_factory=dict)
    competitor_plugin: dict[str, str] = Field(default_factory=dict)
    # Bradley-Terry sufficient statistics (§4, arena/rating.py), already
    # weighted by BT_AUTO_WEIGHT — the fixed (never bootstrap-resampled)
    # contribution every leaderboard rebuild starts from.
    pairwise_wins: dict[str, dict[str, float]] = Field(default_factory=dict)
    pairwise_games: dict[str, dict[str, float]] = Field(default_factory=dict)
